### ISSUE TITLE
Edit the lorem ipsum away from the README.md

### ISSUE THREAD

**Issue by Iikeli** [Iikeli/VuePress-blog#7]
The example lorem ipsum should be edited away from the README.md and add a proper introduction to the tutorial.

**Comment by JulianJason** [comment]
I'll do it

**Comment by JulianJason** [comment]
Is [this](https://github.com/JulianJason/VuePress-blog/commit/69956c56eb7c21c0b0a06245f33bc1a2313889d4) good enough
